### ISSUE TITLE
Uncaught ReferenceError: moment is not defined

### ISSUE THREAD

**Issue by scstraus** [rdehuyss/homeassistant-lovelace-google-calendar-card#23]
Sometimes randomly I get this error in the log and Calendar card decides not to load. Any idea why?

https://MYHOST:8123/local/custom_ui/calendar-card/calendar-card.js?v=1.0.1:10:7 Uncaught ReferenceError: moment is not defined

A lot of times it works fine, but sometimes it does that.

**Comment by HACee** [comment]
I didn't ever get this error, but just upgraded to 0.86.1 and have got it quite a few times now.

**Comment by ozrex75** [comment]
Me too after upgrading to 0.86.1

**Comment by YoinkZed** [comment]
Me too. Happened as well after the 86.1 update.

**Comment by yosilevy** [comment]
It's not random for me. I have calendar card on a view that is not the first one. If I open the GUI it never happens since moment loads before the card since to view the card I need to go to another view. If I refresh the browser when I'm in the view that has the calendar card it ALWAYS fails now.

**Comment by IIIdefconIII** [comment]
is this still maintaned?

**Comment by IIIdefconIII** [comment]
where do you guys have the js file?
i just changed it from /local to
`url: /local/custom_ui/calendar-card/calendar-card.js?v=4`
and it seems to have non more issues, for now

**Comment by YoinkZed** [comment]
> where do you guys have the js file?
> i just changed it from /local to
> `url: /local/custom_ui/calendar-card/calendar-card.js?v=4`
> and it seems to have non more issues, for now

Hi def,
I have it stored the same place as where you have changed it to:
`url: /local/custom_ui/calendar-card/calendar-card.js?v=1.0.1`

The thing I don't understand is your version? I never saw an update with my custom updater and it doesn't look like the js file has been updated lately here on github?

**Comment by YoinkZed** [comment]
Yeah why not. Will give it a try. 
Just weird that if I set another page or move the calendar card to another tab, then I don't get the error, because the moment file will be loaded before it gets called by the calendar card...

**Comment by yosilevy** [comment]
That's still my problem. Refreshing page with calendar-card on it never works.

**Comment by yosilevy** [comment]
Solved it (brute force). Change the set hass function in to these 2 funcs.

  set hass(hass) {
    this._hass = hass;

    if (!this.content) {
      const card = document.createElement('ha-card');
      card.header = this.config.name;
      this.content = document.createElement('div');
      this.content.style.padding = '0 16px 16px';
      card.appendChild(this.content);
      this.appendChild(card);
    }

    this.init();
  }

  init() {
    if(typeof(moment) == "undefined") {
      setTimeout(() => this.init(), 200);
      return;
    }

    moment.locale(this._hass.language);
    this
      .getAllEvents(this.config.entities)
      .then(events => this.updateHtmlIfNecessary(events))
      .catch(error => console.log('error', error));
  }

**Comment by IIIdefconIII** [comment]
Do you have moments js higher then the card module? I do...

**Comment by YoinkZed** [comment]
Where have you 'downloaded' the moments file from?
I think I still use the one that is on this git repo/or the one that are in the link.

**Comment by IIIdefconIII** [comment]
> set hass(hass) {

In what file did you made the change, i tought my problems were away but still having the issue

**Comment by yosilevy** [comment]
In the calendar-card file. Code is above and there's also a pull request pending with my change. You can just copy it.

**Comment by bouwew** [comment]
@yosilevy, thanks! I've used your solution successfully to solve this error in another HA-card.

**Comment by scstraus** [comment]
This cars s is no longer supported so I’m closing
