### ISSUE TITLE
"Custom Element doesn't exist" error when no events found today

### ISSUE THREAD

**Issue by carlchan** [rdehuyss/homeassistant-lovelace-google-calendar-card#7]
As reported initially by @toddw65, if there are no events for today the calendar often fails to load and errors out with "Custom Element doesn't exist".  Seems to happen guaranteed on Android browsers, but desktop Chrome fails only occasionally.

Suspect it has something to do with how getAllEvents fails when no events are found today, but my javascript-fu is weak.

**Comment by rdehuyss** [comment]
Could you send me the logs from the console. I suspect then there must be an error. Click F12 in chrome, console, press CTRL+F5 and watch for anything red. Once I have that input, I can debug the issue.

**Comment by carlchan** [comment]
hmm.  Something I did seems to have fixed it, I can't reproduce it now on any browser.

It still doing it on my Fire Tablet regardless of whether there's an event or not, but I suspect that has to do with the Fire having an outdated Webkit engine, trying to test that on another android device now.  Using debug console on that doesn't show anything unfortunately.

**Comment by rdehuyss** [comment]
Not reproducible

**Comment by scottdarby93** [comment]
I’ve had the same issue on an older iPad, any way around this?

**Comment by scottdarby93** [comment]
Looks like it's the javascript version, is there any way of this working with es5?
